language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  # Install Qt dependencies
  - sudo apt-get install libqt4-dev libsmokeqtgui4-3 libsmokeqt4-dev

script:
  - cl -e '(ql:quickload :trivial-features)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(ql:quickload :qt)'
       -e '(ql:quickload :qt-test)'
       -e '(rt:run-tests)'
